# @see https://github.com/polonel/trudesk/blob/master/docker-compose.yml

networks:
  trudesk:
    name: trudesk

volumes:
  # trudesk-uploads:
  #   name: trudesk-uploads
  # trudesk-backups:
  #   name: trudesk-backups
  trudesk-data:
    name: trudesk-data
  trudesk-database:
    name: trudesk-database
  trudesk-elasticsearch:
    name: trudesk-elasticsearch

services:
  trudesk:
    image: polonel/trudesk:1
    container_name: trudesk
    restart: always
    networks:
      - trudesk
    ports:
      - ${TRUDESK_PORT:-8118}:8118
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    volumes:
      - ./uploads:/usr/src/trudesk/public/uploads
      - ./backups:/usr/src/trudesk/backups
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"

  mongo:
    image: mongo:5.0-focal
    container_name: trudesk_mongodb
    restart: always
    networks:
      - trudesk
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - trudesk-data:/var/lib/mongo
      - trudesk-database:/data/db:rw
    env_file:
      - path: .env
        required: false

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: trudesk_elasticsearch
    restart: always
    networks:
      - trudesk
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - trudesk-elasticsearch:/usr/share/elasticsearch/data
    env_file:
      - path: .env
        required: false
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
