include: [
  # '${SERV:?}/actual/${FILE:?}',
  '${SERV:?}/authentik/${FILE:?}',
  # '${SERV:?}/docmost/${FILE:?}',
  '${SERV:?}/komodo/${FILE:?}',
  # '${SERV:?}/linkace/${FILE:?}',
  # '${SERV:?}/n8n/${FILE:?}',
  # '${SERV:?}/nginx-proxy-manager/${FILE:?}',
  # '${SERV:?}/ntfy/${FILE:?}',
  # '${SERV:?}/open-project/${FILE:?}',
  '${SERV:?}/outline/${FILE:?}',
  # '${SERV:?}/trilium-next/${FILE:?}',
]
