[[stack]]
name = "iardo-vps-iardodev"

[stack.config]
server        = "iardo-vps-iardodev"
branch        = "kubernetes"
repo          = "iardo/srv-kube"
clone_path    = "/etc/srv-kube"
run_directory = "/etc/srv-kube"

file_paths = [
    "serv/actual/docker-compose.yml",
    "serv/authentik/docker-compose.yml",
    "serv/docmost/docker-compose.yml",
    "serv/komodo/docker-compose.yml",
    "serv/linkace/docker-compose.yml",
    "serv/n8n/docker-compose.yml",
    "serv/nginx-proxy-manager/docker-compose.yml",
    "serv/ntfy/docker-compose.yml",
    "serv/open-project/docker-compose.yml",
    "serv/outline/docker-compose.yml",
    "serv/trilium-next/docker-compose.yml",
]
additional_env_files = [
    # HOST
    { track = true,  path = "host/iardo-vps-iardodev/.env" },
    { track = false, path = "host/iardo-vps-iardodev/.env-secrets" },
    # SERV
    { track = true, path = "serv/actual/.env" },
    { track = true, path = "serv/authentik/.env" },
    { track = true, path = "serv/docmost/.env" },
    { track = true, path = "serv/komodo/.env" },
    { track = true, path = "serv/linkace/.env" },
    { track = true, path = "serv/n8n/.env" },
    { track = true, path = "serv/open-project/.env" },
    { track = true, path = "serv/outline/.env" },
]
pre_deploy.shell_mode = false
pre_deploy.command = """
    # Actual
    bash serv/actual/task/task-gen-directories.sh
    bash serv/actual/task/task-set-permissions.sh

    # Linkace
    bash serv/linkace/task/task-gen-directories.sh
    bash serv/linkace/task/task-set-permissions.sh

    # n8n
    bash serv/n8n/task/task-gen-directories.sh
    bash serv/n8n/task/task-set-permissions.sh

    # Nginx Proxy Manager
    bash serv/nginx-proxy-manager/task/task-set-permissions.sh

    # Ntfy
    bash serv/ntfy/task/task-set-initial-files.sh

    # Open Project
    bash serv/open-project/task/task-gen-directories.sh
    bash serv/open-project/task/task-set-permissions.sh

    # Trilium Next
    bash serv/trilium-next/task/task-gen-directories.sh
    bash serv/trilium-next/task/task-set-permissions.sh
"""
