[[stack]]
name = "host-testing"

[stack.config]
server        = "host-testing"
branch        = "kubernetes"
repo          = "iardo/srv-kube"
clone_path    = "/etc/srv-kube"
run_directory = "/etc/srv-kube"

file_paths = [
    "host/@host-testing/komodo-dpl.yml",
]

additional_env_files = [
    # HOST
    { track = true,  path = "host/@host-testing/.env" },
    { track = false, path = "host/@host-testing/.env-secrets" },
    { track = false, path = "host/@host-testing/.env-secrets.local" },
    # SERV
    { track = true, path = "serv/docuseal/.env" },
    { track = true, path = "serv/immich/.env" },
    { track = true, path = "serv/paperless-ngx/.env" },
    { track = true, path = "serv/romm/.env" },
    { track = true, path = "serv/wger/.env" },
    { track = true, path = "serv/wireguard-easy/.env" },
]

pre_deploy.shell_mode = false
pre_deploy.command = """
    [ -f host/@host-testing/.env-secrets.local ] || cp host/@host-testing/.env-secrets host/@host-testing/.env-secrets.local

    # Paperless-ngx
    bash serv/paperless-ngx/task/task-gen-directories.sh
    bash serv/paperless-ngx/task/task-set-permissions.sh

    # Wger
    bash serv/wger/task/task-gen-directories.sh
    bash serv/wger/task/task-set-permissions.sh
"""
