# References
# --------------------
# https://github.com/moghtech/komodo/blob/main/compose/compose.env
# https://github.com/moghtech/komodo/blob/main/compose/mongo.compose.yaml
# https://github.com/moghtech/komodo/blob/main/config/periphery.config.toml

networks:
  komodo:
    name: komodo

volumes:
  komodo-database:
    name: komodo-database
    driver: local
  komodo-dbconfig:
    name: komodo-dbconfig
    driver: local
  komodo-keys:
    name: komodo-keys
    driver: local

services:
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:2
    container_name: komodo-core
    init: true
    restart: unless-stopped
    depends_on:
      - komodo-database
    networks:
      - komodo
    ports:
      - ${KOMODO_WEB_HTTP:-9120}:9120
    volumes:
      - komodo-keys:/config/keys
      - ${KOMODO_PATH_BACKUP:?}:/backups
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-ferretdb:27017
      TZ: ${TIMEZONE:-America/Panama}

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: komodo-periphery
    init: true
    restart: unless-stopped
    depends_on:
      - komodo-core
    networks:
      - komodo
    volumes:
      - komodo-keys:/config/keys
      - /proc:/proc
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    env_file: .env

  # Postgres
  # ----
  komodo-database:
    image: ghcr.io/ferretdb/postgres-documentdb:17
    container_name: komodo-database
    restart: unless-stopped
    networks:
      - komodo
    ports:
      - ${KOMODO_DATABASE:-5432}:5432
    volumes:
      - komodo-database:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${KOMODO_DATABASE_PASSWORD}
      POSTGRES_USER: ${KOMODO_DATABASE_USERNAME}

  komodo-ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.7.0
    container_name: komodo-ferretdb
    restart: unless-stopped
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    depends_on:
      - komodo-database
    networks:
      - komodo
    ports:
      - ${KOMODO_FERRETDB:-27017}:27017
    volumes:
      - komodo-dbconfig:/state
    env_file: .env
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${KOMODO_DATABASE_USERNAME}:${KOMODO_DATABASE_PASSWORD}@komodo-database:5432/postgres

  # MongoDB (Not-Advised)
  # ----
  # komodo-database:
  #   image: mongo
  #   container_name: komodo-database
  #   restart: unless-stopped
  #   command: --quiet --wiredTigerCacheSizeGB 0.25
  #   labels:
  #     komodo.skip: # Prevent Komodo from stopping with StopAllContainers
  #   networks:
  #     - komodo
  #   ports:
  #     - ${KOMODO_DATABASE:-27017}:27017
  #   volumes:
  #     - komodo-database:/data/db
  #     - komodo-dbconfig:/data/configdb
  #   env_file: .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DATABASE_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DATABASE_PASSWORD}
