version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
     - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Panama
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - /mnt/m/Multimedia-C/Film/3D:/MOVIES/3D
      - /mnt/m/Multimedia-C/Film/Anime:/MOVIES/Anime
      - /mnt/m/Multimedia-C/Film/Cartoon:/MOVIES/Cartoon
      - /mnt/m/Multimedia-C/Series/Anime:/SERIES/Anime
    ports:
      - 8096:8096     # HTTP
      - 8920:8920     # HTTPS
      - 7359:7359/udp # Discovery
      - 1900:1900/udp # DLNA UPnP
    restart: unless-stopped

