include: [
  '${SERV:?}/highlight/${FILE:?}',
  '${SERV:?}/mirotalksfu/${FILE:?}',
  '${SERV:?}/nginx-proxy-manager/${FILE:?}',
  '${SERV:?}/paperless-ngx/${FILE:?}',
  '${SERV:?}/passbolt/${FILE:?}',
  '${SERV:?}/portainer/${FILE:?}',
  '${SERV:?}/postal/${FILE:?}',
]
