# References
# --------------------
# https://github.com/dgtlmoon/changedetection.io/blob/master/docker-compose.yml

networks:
  changedetection:
    name: changedetection

volumes:
  changedetection-web:
    name: changedetection-web

services:
  changedetection-web:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection-web
    restart: unless-stopped
    # If WEBDRIVER or PLAYWRIGHT are enabled, changedetection container depends on that
    depends_on:
      changedetection-sockpuppet:
        condition: service_started
      changedetection-selenium:
        condition: service_started
    networks:
      - changedetection
    ports:
      - ${CHANGEDETECTION_WEB_HTTP:-5000}:5000
    volumes:
      # - ./cert:/cert
      # Configurable proxy list support
      # https://github.com/dgtlmoon/changedetection.io/wiki/Proxy-configuration#proxy-list-support
      # - ./conf/proxies.json:/datastore/proxies.json
      - changedetection-web:/datastore
    env_file: .env
    environment:
      PORT: 5000
      # LISTEN_HOST: 0.0.0.0
      # It uses the "playwright" protocol
      PLAYWRIGHT_DRIVER_URL: ws://changedetection-sockpuppet:3000
      # Alternative WebDriver/selenium URL, do not use "'s or 's!
      # NOTE: Old, deprecated, does not support screenshots very well
      WEBDRIVER_URL: http://changedetection-selenium:4444/wd/hub
      # HTTP_PROXY: socks5h://10.10.1.10:1080  # Proxy Support
      # HTTPS_PROXY: socks5h://10.10.1.10:1080 # Proxy Support
      # NO_PROXY: "localhost,192.168.0.0/24"   # An exclude list (useful for notification URLs above)
      # BASE_URL: ${CHANGEDETECTION_PUBLIC_URL_WEB:-https://mysite.com}
      TZ: ${CHANGEDETECTION_TIMEZONE:-America/Panama}

  # Sockpuppetbrowser is chrome wrapped in an API for allowing fast fetching of web-pages.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME, be sure to enable "PLAYWRIGHT_DRIVER_URL"
  # 
  # Playwright proxy settings playwright_proxy_server, playwright_proxy_bypass, 
  #                           playwright_proxy_username, playwright_proxy_password
  # https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-proxy
  changedetection-sockpuppet:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: changedetection-sockpuppet
    restart: unless-stopped
    cap_add:
      # SYS_ADMIN might be too much, but it can be needed on your platform
      # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
      - SYS_ADMIN
    networks:
      - changedetection
    env_file: .env
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1024
      SCREEN_DEPTH: 16
      MAX_CONCURRENT_CHROME_PROCESSES: 10

  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  # NOTE: Works well but is deprecated, does not fetch full page screenshots (doesnt work with Visual Selector)
  #       Does not report status codes (200, 404, 403) and other issues
  # 
  # NOTE: Now working on arm64 (needs testing on rPi - tested on Oracle ARM instance)
  #       replace image with seleniarm/standalone-chromium:4.0.0-20211213
  # 
  # WebDriver proxy settings webdriver_proxyType, webdriver_ftpProxy, webdriver_noProxy,
  #                          webdriver_proxyAutoconfigUrl, webdriver_autodetect,
  #                          webdriver_socksProxy, webdriver_socksUsername, webdriver_socksVersion, webdriver_socksPassword
  # https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.proxy
  changedetection-selenium:
    image: selenium/standalone-chrome:4
    container_name: changedetection-selenium
    restart: unless-stopped
    networks:
      - changedetection
    volumes:
      # Workaround to avoid the browser crashing inside docker container
      # https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    env_file: .env
    environment:
      VNC_NO_PASSWORD: 1
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      SCREEN_DEPTH: 24
      CHROME_OPTIONS: |
        --window-size=1280,1024
        --headless
        --disable-gpu
