# REFERENCE
# https://github.com/almarklein/timetagger/blob/main/deploy/docker-compose.yml

x-env: &web
  ports:
    - "${PORT_TIMETAGGER:-8092}:80"
  environment:
    TIMETAGGER_BIND: "${TIMETAGGER_BIND:-0.0.0.0:80}"
    TIMETAGGER_CREDENTIALS: "${TIMETAGGER_CREDENTIALS:-test:$$2a$$08$$0CD1NFiIbancwWsu3se1v.RNR/b7YeZd71yg3cZ/3whGlyU6Iny5i}"
    TIMETAGGER_DATADIR: "${TIMETAGGER_DATADIR:-/root/_timetagger}"
    TIMETAGGER_LOG_LEVEL: "${TIMETAGGER_LOG_LEVEL:-info}"

networks:
  # If the network does not exist run next command:
  # docker network create --driver=bridge reverse-proxy
  reverse-proxy:
    name: reverse-proxy
    external: true

services:
  timetagger-web:
    <<: *web
    image: ghcr.io/almarklein/timetagger:v25.06.1
    container_name: timetagger-web
    restart: unless-stopped
    networks:
      - reverse-proxy
    volumes:
      - ./data:/root/_timetagger
