# REFERENCE
# https://github.com/linkwarden/linkwarden/blob/main/docker-compose.yml
# https://docs.linkwarden.app/self-hosting/installation

networks:
  # If the network does not exist run next command:
  # docker network create --driver=bridge reverse-proxy
  reverse-proxy:
    name: reverse-proxy
    external: true

volumes:
  aplication-data:
    name: linkwarden-data
  database-data:
    name: linkwarden-database

services:
  linkwarden-web:
    container_name: linkwarden-web
    image: ghcr.io/linkwarden/linkwarden:v2.5.3
    restart: unless-stopped
    depends_on:
      - linkwarden-database
    networks:
      - reverse-proxy
    ports:
      # Server only exports 3000, it can't be changed at the moment.
      # https://github.com/linkwarden/linkwarden/issues/462#issuecomment-1937111674
      - ${LINKWARDEN_PORT:-5173}:3000
    volumes:
      - ./logs:/logs
      - aplication-data:/data/data
    env_file: .env

  linkwarden-database:
    container_name: linkwarden-database
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - reverse-proxy
    ports:
      - ${POSTGRES_PORT:-8090}:8090
    volumes:
      - ./backups:/backups
      - ./logs:/logs
      - database-data:/var/lib/postgresql/data
    env_file: .env
