# REFERENCE
# https://github.com/actualbudget/actual-server/blob/master/docker-compose.yml
# https://actualbudget.org/docs/install/docker/

networks:
  # If the network does not exist run next command:
  # docker network create --driver=bridge reverse-proxy
  reverse-proxy:
    name: reverse-proxy
    external: true

services:
  actual-web:
    image: docker.io/actualbudget/actual-server:23.10.0-alpine
    container_name: actual-web
    restart: unless-stopped
    networks:
      - reverse-proxy
    ports:
      - ${ACTUAL_PORT:-5006}:5006
    volumes:
      - ./data:/data
    env_file: .env
