[[stack]]
name = "iardo-vps-iardoo"

[stack.config]
server        = "iardo-vps-iardoo"
branch        = "kubernetes"
repo          = "iardo/srv-kube"
clone_path    = "/etc/srv-kube"
run_directory = "/etc/srv-kube"

file_paths = [
    "host/iardo-vps-iardoo/komodo-dpl.yml",
]

additional_env_files = [
    # HOST
    { track = true,  path = "host/iardo-vps-iardoo/.env" },
    { track = false, path = "host/iardo-vps-iardoo/.env-secrets" },
    { track = false, path = "host/iardo-vps-iardoo/.env-secrets.local" },
    # SERV
    { track = true, path = "serv/actual/.env" },
    { track = true, path = "serv/linkace/.env" },
]

pre_deploy.shell_mode = false
pre_deploy.command = """
    [ -f host/iardo-vps-iardoo/.env-secrets.local ] || cp host/iardo-vps-iardoo/.env-secrets host/iardo-vps-iardoo/.env-secrets.local

    # Actual
    bash serv/actual/task/task-gen-directories.sh
    bash serv/actual/task/task-set-permissions.sh

    # Linkace
    bash serv/linkace/task/task-gen-directories.sh
    bash serv/linkace/task/task-set-permissions.sh

    # Ntfy
    bash serv/ntfy/task/task-set-initial-files.sh
"""
