FROM vandot/alpine-bash:3 AS code

RUN apk add --no-cache git
RUN git clone https://github.com/pschlan/cron-job.org /code


FROM node:21 AS build

ARG CJO_PROJECT_NAME
ENV CJO_PROJECT_NAME $CJO_PROJECT_NAME
ARG CJO_BASE_URL
ENV CJO_BASE_URL $CJO_BASE_URL

RUN mkdir -p /src/cron-job.org/frontend

COPY --from=code /code/frontend/ /src/cron-job.org/frontend
COPY --from=code /code/frontend/docker/Config.js /src/cron-job.org/frontend/src/utils/
COPY --from=code /code/frontend/docker/update-frontend-config /usr/local/bin/

RUN chmod 0755 /usr/local/bin/update-frontend-config
RUN            /usr/local/bin/update-frontend-config

WORKDIR /src/cron-job.org/frontend
RUN npm ci && npm run build


FROM nginx:stable-alpine3.21

COPY --from=build /src/cron-job.org/frontend/build/ /usr/share/nginx/html/
COPY --from=code /code/frontend/docker/default.conf /etc/nginx/conf.d/default.conf
COPY --from=code /code/frontend/src/resources/logo.png /usr/share/nginx/html
