# References
# --------------------
# https://github.com/pi-hole/docker-pi-hole/blob/master/examples/docker-compose-caddy-proxy.yml

networks:
  pihole:
    name: pihole

services:
  pihole-web:
    image: pihole/pihole:latest
    container_name: pihole-web
    restart: unless-stopped
    cap_add:
      # Recommended but not required (DHCP needs NET_ADMIN)
      # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - NET_ADMIN
    # network_mode: host
    networks:
      - pihole
    ports:
      - ${PIHOLE_WEB_HTTP:-80}:80/tcp # Panel
      - ${PIHOLE_DNS_TCP:-53}:53/tcp  # DNS
      - ${PIHOLE_DNS_UDP:-53}:53/udp  # DNS
      - ${PIHOLE_DHCP:-67}:67/udp     # Only required if you are using Pi-hole as your DHCP server
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d     
    environment:
      FTLCONF_webserver_api_password: pihole # Dummy
      TZ: ${TIMEZONE:-America/Panama}
