# References
# --------------------
# https://github.com/P3TERX/Aria2-Pro-Docker/blob/master/docker-compose.yml

networks:
  aria2-pro:
    name: aria2-pro

services:
  aria2-pro-server:
    image: p3terx/aria2-pro
    container_name: aria2-pro-server
    restart: unless-stopped
    # Since Aria2 will continue to generate logs,
    # limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - aria2-pro
    ports:
      - ${ARIA2_PRO_RPC:-6800}:6800          # RPC protocol
      - ${ARIA2_PRO_MUSE_TCP:-6888}:6888     # MUSE peer-to-peer
      - ${ARIA2_PRO_MUSE_UDP:-6888}:6888/udp # MUSE peer-to-peer
    volumes:
      - ./conf:/config
      - ./data/downloads:/downloads
    env_file: .env
    environment:
      LISTEN_PORT: 6888
      PGID: 65534
      PUID: 65534
      RPC_PORT: 6800
      UMASK_SET: 022
      TZ: ${TIMEZONE:-America/Panama}

  aria2-pro-web:
    image: p3terx/ariang
    container_name: aria2-pro-web
    restart: unless-stopped
    command: --port 6880 --ipv6
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - aria2-pro
    ports:
      - ${ARIA2_PRO_WEB_HTTP:-6880}:6880
