[[stack]]
name = "iardo-macbook"

[stack.config]
server        = "iardo-macbook"
branch        = "kubernetes"
repo          = "iardo/srv-kube"
clone_path    = "/etc/srv-kube"
run_directory = "/etc/srv-kube"

file_paths = [
    "host/iardo-macbook/docker-compose.yml",
]

additional_env_files = [
    # HOST
    { track = true,  path = "host/iardo-macbook/.env" },
    { track = false, path = "host/iardo-macbook/.env-secrets" },
    { track = false, path = "host/iardo-macbook/.env-secrets.local" },
    # SERV
    { track = true, path = "serv/komodo/.env" },
]

pre_deploy.shell_mode = false
pre_deploy.command = """
    [ -f host/iardo-macbook/.env-secrets.local ] || cp host/iardo-macbook/.env-secrets host/iardo-macbook/.env-secrets.local
"""
