[[stack]]
name = "iardo-macbook"

[stack.config]
server        = "iardo-macbook"
branch        = "kubernetes"
repo          = "iardo/srv-kube"
clone_path    = "/etc/srv-kube"
run_directory = "/etc/srv-kube"

file_paths = []
additional_env_files = [
    # HOST
    { track = true,  path = "host/iardo-macbook/.env" },
    { track = false, path = "host/iardo-macbook/.env-secrets" },
    # SERV
    { track = true, path = "serv/komodo/.env" },
]
pre_deploy.shell_mode = false
pre_deploy.command = """ """
