# References
# --------------------
# https://docs.linkwarden.app/self-hosting/installation
# https://github.com/linkwarden/linkwarden/blob/main/docker-compose.yml


# Warning ⚠️
# --------------------
# Memory Hungry
# ----
# Linkwarden uses Playwright to obtain some data from the sites,
# this spawns a headless browser process
# and as you may know, modern browsers consumes a lot of RAM,
# therefore, it is very memory instensive application.
# 
# Be wary of this if you intent to use this in a VPS,
# you will need above ~4GBs of RAM to be able to use it.
# 
# https://playwright.dev/
# 


networks:
  linkwarden:
    name: linkwarden

volumes:
  linkwarden-archives:
    name: linkwarden-archives
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/archives
  linkwarden-database:
    name: linkwarden-database

services:
  linkwarden-web:
    image: ghcr.io/linkwarden/linkwarden:v2.5.3
    container_name: linkwarden-web
    restart: unless-stopped
    depends_on:
      - linkwarden-database
    networks:
      - linkwarden
    ports:
      - ${LINKWARDEN_WEB_HTTP:-5173}:3000
    volumes:
      - ./logs:/logs
      - linkwarden-archives:/data/data/archives
    env_file: .env
    environment:
      NEXT_PUBLIC_DISABLE_REGISTRATION: ${LINKWARDEN_DISABLE_REGISTRATION:-false}

  linkwarden-database:
    image: postgres:16-alpine
    container_name: linkwarden-database
    restart: unless-stopped
    networks:
      - linkwarden
    ports:
      - ${LINKWARDEN_DATABASE:-8090}:8090
    volumes:
      - ./data/backup:/backups
      - ./logs:/logs
      - linkwarden-database:/var/lib/postgresql/data
    env_file: .env
    environment:
      PGPORT: 8090
      POSTGRES_DB: ${LINKWARDEN_POSTGRES_NAME:?}
      POSTGRES_PASSWORD: ${LINKWARDEN_POSTGRES_PASS:?}
      POSTGRES_USER: ${LINKWARDEN_POSTGRES_USER:?}
  