# References
# --------------------
# https://github.com/NginxProxyManager/nginx-proxy-manager?tab=readme-ov-file#quick-setup


# Credentials
# --------------------
# Sometimes on first login you could get an error 502 bad gateway,
# just wait some minutes and try again.
#
# user: admin@example.com
# pass: changeme

# networks:
  # If the network does not exist run next command:
  # docker network create --driver=bridge reverse-proxy
  # reverse-proxy:
  #   name: reverse-proxy
  #   external: true

services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:2
    container_name: nginx-proxy-manager
    platform: linux/amd64
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - reverse-proxy
    ports:
      - ${NGINX_PROXY_MANAGER_PANEL:-81}:81   # Web-interface
      - ${NGINX_PROXY_MANAGER_HTTP:-80}:80
      - ${NGINX_PROXY_MANAGER_HTTPS:-443}:443
    volumes:
      - ./data:/data
      - ./cert:/etc/letsencrypt
